# Generated by Django 4.0.6 on 2022-08-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UCR_Testing',
            fields=[
                ('title', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, default='New use case rule', max_length=256, null=True)),
                ('author', models.CharField(blank=True, default='AYSOME IT Security', max_length=256, null=True)),
                ('index', models.CharField(default='main', max_length=256)),
                ('sourcetype', models.CharField(default='api', max_length=256)),
                ('variables', models.CharField(blank=True, max_length=256, null=True)),
                ('search_query', models.TextField()),
                ('threshhold', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'UCR',
                'verbose_name_plural': 'UCRs',
            },
        ),
    ]
