# Generated by Django 4.0.6 on 2022-08-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ucr_testing',
            old_name='search_query',
            new_name='testing_query',
        ),
    ]
