# API Settings file
PRIMARY_API = 'splunk'

## Splunk API Settings
SPLUNK_API = 'On'
SPLUNK_API_HOST = '127.0.0.1'
SPUNK_API_PORT = '8089'
SPLUNK_API_TOKEN = 'eyJraWQiOiJzcGx1bmsuc2VjcmV0IiwiYWxnIjoiSFM1MTIiLCJ2ZXIiOiJ2MiIsInR0eXAiOiJzdGF0aWMifQ.eyJpc3MiOiJhZG1pbiBmcm9tIDg1Mzg4ZWVjNjkxNiIsInN1YiI6ImFkbWluIiwiYXVkIjoiYXBpIiwiaWRwIjoiU3BsdW5rIiwianRpIjoiNGUzYjVhZjU4NjNkNGY4NjVhNWVmOWIyZTNkNGM1NmFlYWE5YTcwZGZkN2E3ZWI4MWI0OWVkNzMwOWMxZDFhMSIsImlhdCI6MTY1NzA0MzM2MCwiZXhwIjoxNjU5NjM1MzYwLCJuYnIiOjE2NTcwNDMzNjB9.1d-79aHvljvoTS5sQkBMpZQsMNIN3jQiil6G0yPI7FnsFc2jqojzUaqtMin-FAtrrYNxPMpfjixB4naRG53tEg'
SPLUNK_API_AUTOLOGIN = True
SPLUNK_API_VERSION = '8.2'
SPLUNK_API_SCHEME = 'https'
SPLUNK_API_APP = 'search'

## ELK API Settings
ELK_API = 'Off'