import os
import sys
sys.path.append(os.getcwd())

from siem.settings import TIME_ZONE

# API Settings file
PRIMARY_API = 'splunk'
TIMEZONE = TIME_ZONE

## Splunk API Settings
SPLUNK_API = 'On'
SPLUNK_API_HOST = '127.0.0.1'
SPUNK_API_PORT = '8089'
SPLUNK_API_TOKEN = 'eyJraWQiOiJzcGx1bmsuc2VjcmV0IiwiYWxnIjoiSFM1MTIiLCJ2ZXIiOiJ2MiIsInR0eXAiOiJzdGF0aWMifQ.eyJpc3MiOiJhZG1pbiBmcm9tIDRlMGYxMDIzMjIyMSIsInN1YiI6ImFkbWluIiwiYXVkIjoidGVzdCIsImlkcCI6IlNwbHVuayIsImp0aSI6ImI4YTJmMTYwNmQ5OGQyYTgwMjY1MTQ5ODU5OGZjYTE4N2JmNzdhNjQ5NDc3MTBmOGUwYmE1YjRhMjFjYTk0MGYiLCJpYXQiOjE2NTg4OTg2MTgsImV4cCI6MTY2MTQ5MDYxOCwibmJyIjoxNjU4ODk4NjE4fQ.bUlxsbyYpGjS_Po5bxIGSKTlDC1vir6p9Q_GQ8UBIzwDvBKXEZjeVfLfeZynBkZaRYYYvS3Ba3Ke1wpPZ43ixQ'
SPLUNK_API_AUTOLOGIN = True
SPLUNK_API_VERSION = '8.2'
SPLUNK_API_SCHEME = 'https'
SPLUNK_API_APP = 'search'
SPLUNK_RESULTS_INDEX = 'main'
SPLUNK_RESULTS_SOURCETYPE = 'api-connection'

## ELK API Settings
ELK_API = 'Off'