# Generated by Django 4.0.5 on 2022-07-14 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('title', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, default='New alert', max_length=256, null=True)),
                ('raw_event', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('title', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, default='New correlation', max_length=256, null=True)),
                ('author', models.CharField(blank=True, default='AYSOME IT Security', max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('title', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, default='New group', max_length=256, null=True)),
                ('index', models.CharField(max_length=64)),
                ('sourcetype', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UCR',
            fields=[
                ('title', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, default='New use case rule', max_length=256, null=True)),
                ('author', models.CharField(blank=True, default='AYSOME IT Security', max_length=256, null=True)),
                ('cron', models.CharField(default='30 * * * *', max_length=256)),
                ('search_terms', models.CharField(blank=True, max_length=256, null=True)),
                ('search_query', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.group')),
            ],
        ),
        migrations.CreateModel(
            name='Enrichment',
            fields=[
                ('title', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, default='New enrichment', max_length=256, null=True)),
                ('author', models.CharField(blank=True, default='AYSOME IT Security', max_length=256, null=True)),
                ('required_fields', models.CharField(max_length=256)),
                ('search_query', models.TextField()),
                ('required_groups', models.ManyToManyField(to='backend.group')),
            ],
        ),
    ]
