# Generated by Django 4.0.5 on 2022-07-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('backend', '0001_initial'), ('backend', '0002_alert_description_alert_raw_event_and_more'), ('backend', '0003_alter_alert_description_and_more'), ('backend', '0004_alter_alert_description_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('index', models.CharField(max_length=64)),
                ('sourcetype', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='New group', max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, default='New alert', max_length=256, null=True)),
                ('raw_event', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, default='New correlation', max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, default='New enrichment', max_length=256, null=True)),
                ('required_fields', models.CharField(default=None, max_length=256)),
                ('required_groups', models.ManyToManyField(to='backend.group')),
                ('search_query', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='UCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('search_query', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.group')),
                ('description', models.CharField(blank=True, default='New use case rule', max_length=256, null=True)),
            ],
        ),
    ]
