# Generated by Django 4.0.5 on 2022-07-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='author',
            field=models.CharField(blank=True, default='AYSOME IT Security', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='author',
            field=models.CharField(blank=True, default='AYSOME IT Security', max_length=256, null=True),
        ),
    ]
