# Generated by Django 4.0.5 on 2022-07-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='description',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='raw_event',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correlation',
            name='description',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrichment',
            name='description',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrichment',
            name='required_fields',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrichment',
            name='required_groups',
            field=models.ManyToManyField(to='backend.group'),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='search_query',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ucr',
            name='description',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
