# Generated by Django 4.0.5 on 2022-07-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_squashed_0004_alter_alert_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='raw_event',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='enrichment',
            name='required_fields',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='enrichment',
            name='search_query',
            field=models.TextField(),
        ),
    ]
