# Generated by Django 4.0.5 on 2022-07-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_alert_raw_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlation',
            name='author',
            field=models.CharField(blank=True, default='AYSOME IT Security', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='author',
            field=models.CharField(blank=True, default='AYSOME IT Security', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ucr',
            name='author',
            field=models.CharField(blank=True, default='AYSOME IT Security', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ucr',
            name='search_terms',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
