# Generated by Django 4.0.5 on 2022-07-15 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alert_author_group_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrichment',
            old_name='required_groups',
            new_name='group',
        ),
    ]
