# Generated by Django 4.0.5 on 2022-07-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alert_description_alert_raw_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='description',
            field=models.CharField(default='New alert', max_length=256),
        ),
        migrations.AlterField(
            model_name='correlation',
            name='description',
            field=models.CharField(default='New correlation', max_length=256),
        ),
        migrations.AlterField(
            model_name='enrichment',
            name='description',
            field=models.CharField(default='New enrichment', max_length=256),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(default='New group', max_length=256),
        ),
        migrations.AlterField(
            model_name='ucr',
            name='description',
            field=models.CharField(default='New use case rule', max_length=256),
        ),
    ]
