# Generated by Django 4.0.6 on 2022-07-21 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_required_groups_enrichment_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': 'alert', 'verbose_name_plural': 'alerts'},
        ),
        migrations.AlterModelOptions(
            name='correlation',
            options={'verbose_name': 'correlation', 'verbose_name_plural': 'correlations'},
        ),
        migrations.AlterModelOptions(
            name='enrichment',
            options={'verbose_name': 'enrichment', 'verbose_name_plural': 'enrichments'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterModelOptions(
            name='ucr',
            options={'verbose_name': 'UCR', 'verbose_name_plural': 'UCRs'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='index',
        ),
        migrations.RemoveField(
            model_name='group',
            name='sourcetype',
        ),
        migrations.AddField(
            model_name='group',
            name='search_query_prefix',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ucr',
            name='cron_next_run',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 7, 15, 25, 650086)),
        ),
        migrations.AddField(
            model_name='ucr',
            name='threshhold',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ucr',
            name='threshhold_group_by_fields',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
