# Generated by Django 4.0.5 on 2022-07-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_correlation_author_enrichment_author_ucr_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucr',
            name='cron',
            field=models.CharField(default='30 * * * *', max_length=256),
        ),
    ]
