# Generated by Django 4.0.5 on 2022-07-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_alert_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='description',
            field=models.CharField(blank=True, default='New alert', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='correlation',
            name='description',
            field=models.CharField(blank=True, default='New correlation', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='enrichment',
            name='description',
            field=models.CharField(blank=True, default='New enrichment', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, default='New group', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ucr',
            name='description',
            field=models.CharField(blank=True, default='New use case rule', max_length=256, null=True),
        ),
    ]
