# Generated by Django 4.0.6 on 2022-07-28 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_correlation_required_fields_correlation_search_query_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucr',
            name='cron_next_run',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 7, 58, 33, 213549, tzinfo=utc)),
        ),
    ]
