# Generated by Django 4.0.6 on 2022-07-28 08:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_ucr_cron_previous_run_alter_ucr_cron_next_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucr',
            name='cron_next_run',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 8, 3, 27, 275036, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ucr',
            name='cron_previous_run',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 8, 3, 27, 275072, tzinfo=utc), editable=False),
        ),
    ]
